//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation() { }
        public Reservation(int idU, int idH, DateTime? startR, DateTime? endR)
        {
            this.idU = idU;
            this.idH = idH;
            this.startR = startR;
            this.endR = endR;
        }

        public int idR { get; set; }
        public int idU { get; set; }
        public int idH { get; set; }
        public Nullable<System.DateTime> startR { get; set; }
        public Nullable<System.DateTime> endR { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
